### ISSUE TITLE
Specific list of supported systems?

### ISSUE THREAD

**Issue by MouseProducedGames** [gooofy/aqb#10]
# My concern

The readme states that "classic 68k Amiga systems" are targeted by the compiler; however, this may still leave room for confusion. For example, while I can guess that the Amiga 500 is very likely supported, I am much less sure about, for example, the CD32, and less sure about the A4000.

# Suggestion to fix

A markdown table listing each system, whether it is supported, and the degree of support, such as a percentile; red/yellow/green; bronze/silver/gold/full; and/or a notes and caveats column.

# How I think this will help

+ It will assist users with an overview of the current support state of a system, and how well AQB can be expected to run on that system.
+ It will assist contributors by providing an idea of where to focus their efforts.
  + A contributor who has improved an area of support, can then raise an issue or PR to have the support state of that system changed; which can notify both users and contributors of an improvement in the level of support.

**Comment by gooofy** [comment]
AQB is aiming to be a well behaved Amiga application adhering to Commodore's guidelines for Amiga OS compliant programming so it should run on all (classic) Amiga systems as long as they meet the minimum requirements. From what I hear it also runs on AROS and to some degree on AmigaOS 4.x and MorphOS.
