### ISSUE TITLE
Specific CPU support?

### ISSUE THREAD

**Issue by MouseProducedGames** [gooofy/aqb#11]
# My concern

Certain 68k CPUs do not have features other 68k CPUs have; for example, the 68030 does not have floating-point. While this was typically provided through a 68881 or 68882 add-in floating-point chip, this is not guaranteed.

# Thoughts on fixing

Some indicator of how this may be handled, such as:

+ Only supporting CPUs such as the 68030 if they come with a floating-point unit.
+ Noting that software floating-point support may be required on some CPUs.
+ A setting or option that returns a compiler error on floating-point, thus allowing a program to be compiled without it.

**Comment by gooofy** [comment]
My goal is to support all 68k CPUs, not just specific ones. For now I am simply targeting the 68000, no FPU or MMU required so the IDE as well as the binaries produced should run on all configurations.

I may add FPU support and/or optimized code generation for specific CPUs later, but that is not a priority right now.

I am also considering taking advantage of a MMU (if present) in AQB's debugger but that is also not very high on the list.
