### ISSUE TITLE
Don't use warning level but 20

### ISSUE THREAD

**Issue by polluks** [gooofy/aqb#13]
https://github.com/gooofy/aqb/blob/c977265787c3e3a19133b20b0e5d3de217adecc0/src/compiler/aqb.c#L105
https://github.com/gooofy/aqb/blob/2a9817fd10166f9411153c7879ddbc1b4d1fd10d/src/compiler/ide.c#L1448
https://github.com/gooofy/aqb/blob/a3efd14e457b49b12533261f1c19d350b9665324/src/compiler/util.c#L99

**Comment by gooofy** [comment]
thanks for the report, should be fixed now

https://github.com/gooofy/aqb/commit/e637abc411e22548e6b234d4a6a20344b1d6d33b
