### ISSUE TITLE
OPTION BREAK OFF: keeps catching CTRL-C

### ISSUE THREAD

**Issue by marcoslm** [gooofy/aqb#14]
I added this option at top of code, but it keeps breaking the execution when CTRL-C is pressed. It seems that this istruction is ignored.

Thank you very much for your effort and dedication on this, AQB is a fantastic and promising project.

**Comment by gooofy** [comment]
Disabling runtime CTRL-C checks is not what OPTION BREAK OFF does: it simply disables extra code generated by the compiler which enables CTRL-C checking during (potentially endless) loops and recursive calls. Without that extra code the runtime will still be able to handle CTRL-C during message processing, i/o calls etc.

That said, I have now added an "ON BREAK CALL" statement to the runtime. You can use this statement to register a custom handler which may call "RESUME NEXT" to ignore CTRL-C signals altogether.

Here is tutorial code which illustrates how this will work in the upcoming 0.8.1 release:

https://github.com/gooofy/aqb/blob/master/tutorial/CtrlC.bas

**Comment by marcoslm** [comment]
Thank you very much for the clarification. I look forward to new releases.

**Comment by gooofy** [comment]
release is out, issue should be fixed.
