### ISSUE TITLE
Sprites not working in screen modes >15Khz

### ISSUE THREAD

**Issue by marcoslm** [gooofy/aqb#16]
I tested the "Sprite tutorials" which opens a window in Workbench screen. My Workbench runs in **DBNTSC** screen mode.

> SpriteDemo1 : Sprite not displayed
> SpriteDemo2 : Runtime error 200 at "ILBM LOAD SPRITE"
> SpriteDemo3 : Sprite not displayed

This occurs in screen modes with a horizontal frequency greater than15Khz.

**Comment by gooofy** [comment]
sorry, cannot reproduce this - I just tried DBLNTSC (640x400) as well as PRODUCTIVITY (640x480) and SpriteDemo1 works just as it should.

**Comment by marcoslm** [comment]
I have found why. Test this modes in combination with "VGA Only" monitor.

**Comment by gooofy** [comment]
thanks for the additional info, I can reproduce the issue now. However, I doubt there is much I can do about this - disappearing sprites seem to be normal for these modes:

https://eab.abime.net/showthread.php?t=32725&highlight=dblntsc+sprites

indeed, I tried the "ssprite" RKRM example with this setup and it suffers the same issue.

**Comment by blackborn66** [comment]
I also didn't see the sprites.
Reason is for me, that I use higher color depth and resolution in UAE.
I added a standard SCREEN in every sprite demo and it works for me.
Maybe goofy can pull this from my fork so other testers will not stumble over it.

**Comment by gooofy** [comment]
Opening a custom screen is a good idea - I have pulled your changes now, thanks for your contibution :)
