### ISSUE TITLE
IDE crash

### ISSUE THREAD

**Issue by blackborn66** [gooofy/aqb#24]
I searched for near an hour for a simple stupid fail I made.
If you declare a constant and assign a value later, this happens ;)
I think the compiler should help the devs to find these things.
BTW: I like AQB quite a lot!

example:

`CONST AS INTEGER n = 5`
`PRINT i`
`i = 4`

in 0.8.2:
> assertion "FALSE" failed: file "codegen.c", line 3509, function: CG_transAssignment
Program aborted

**Comment by gooofy** [comment]
should now be fixed:

https://github.com/gooofy/aqb/commit/431a198ca7f4cb4807b4504d947da28cc65e3cbd

**Comment by blackborn66** [comment]
Yes it's fixed
