### ISSUE TITLE
new crash in the oop branch

### ISSUE THREAD

**Issue by blackborn66** [gooofy/aqb#45]
all programs compile, but some crash on start.
All GadToolsTutorials have this problem:
```
assertion " last_hunk_slot < MAX_NUM_HUNKS"
function: load_hunk_header
```

**Comment by gooofy** [comment]
ah, never tried running them from inside the IDE #-)

I have increased the max number of hunks now

a7fac66d296e4b422ace657dc65c6487bfd29a0f

please try again if this fixes the issue for you

**Comment by blackborn66** [comment]
YES!

it helped.
all programs running, but in GadToolsTutorial6 the CGTPalette-gadget makes trouble!
If I comment this one out there, all other stuff is running.

I don't need it yet - so I can continue with the other stuff ...

**Comment by gooofy** [comment]
a75696db8515618ca66d88292c8a814359a99aa1 should fix the palette gadget isse, please try again

**Comment by blackborn66** [comment]
looks good now!

**Comment by gooofy** [comment]
excellent, thanks for your feedback. I have merged the oop branch into master now.
