### ISSUE TITLE
STR$(boolVar)

### ISSUE THREAD

**Issue by blackborn66** [gooofy/aqb#48]
On my hunt for a bug I stumbled in this trap
It looks like only the last BOOLEAN in DIM expression is treated as a real BOOLEAN
 ```
OPTION EXPLICIT

DIM b0, b1, b2 AS Boolean
TRACE b0, b1, b2
PRINT b0, b1, b2
TRACE STR$(b0);STR$(b1);STR$(b2)
TRACE STR$(b0)+STR$(b1)+STR$(b2)
DIM s AS string = STR$(b0)+STR$(b1)+STR$(b2)
TRACE "s1: "; s
s = STR$(b2)
s = s + STR$(b1)
s = s + STR$(b0)
TRACE "s2: "; s

DIM b4 AS Boolean
DIM b5 AS Boolean
TRACE b4, b5
 ```

**Comment by gooofy** [comment]
actually, I suspect this behavior is correct even if it is very counter-intuitive.

the statement

DIM b0, b1, b2 AS BOOLEAN

is equivalent to

DIM b0
DIM b1
DIM b2 AS BOOLEAN

which implies auto-typing for b0 and b1. auto-typing is based on the identifier's suffix (e.g. $ for i$ -> INTEGER), or, if there is none (as in this case), SINGLE.

I recommend using the alternative syntax

DIM AS BOOLEAN b0, b1, b2

which will lead to the expected result

**Comment by blackborn66** [comment]
understand
okay!
