### ISSUE TITLE
Build problem: AQB: env var not set

### ISSUE THREAD

**Issue by gylead** [gooofy/aqb#6]
Sorry for reporting that many build problems. I really love the idea of this project and would like to contribute so I try to get this building on my machine.

Here is another build problem, I do not know (yet) where this is coming from:

```
cp startup.o /home/jochen/snap/fsuae/common/FS-UAE/hdd/Exchange/aqb/lib
../../..//target/x86_64-linux/bin/aqb -d none -s _brt.sym _brt.bas
AQB: env var not set.

make[3]: *** [Makefile:11: _brt.sym] Fehler 1
make[3]: Verzeichnis „/home/jochen/projects/amiga/aqb/src/lib/_brt“ wird verlassen

```

**Comment by gylead** [comment]
I "fixed" this issue by adding

`export AQB = $(SELF_DIR)`

to config.mk before the definition of variable AQB. The only concern I have is the double use of AQB as an evnironment variable and an intern variable of the Makefile. It seems to work though.

**Comment by gooofy** [comment]
actually I just have a export AQB=... line in my ~/.bashrc, but your solution is much cleaner so I have incorporated it into config.mk.tmpl now - thanks! :)
